import dynamic from 'next/dynamic';
import Head from 'next/head';
import 'swagger-ui-react/swagger-ui.css';

const SwaggerUI = dynamic<{ url: string }>(import('swagger-ui-react'), {
  ssr: false,
});

export default function Index() {
  return (
    <div>
      <Head>
        <title>VOI NFT Indexer API</title>
        <meta name="description" content="Generated by flippingalgos.xyz" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SwaggerUI url="/api/doc" />
    </div>
  );
}